//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memba.Files.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memba.Files.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a definition file for this id..
        /// </summary>
        internal static string BLExceptionDefinitionExists {
            get {
                return ResourceManager.GetString("BLExceptionDefinitionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file guid..
        /// </summary>
        internal static string BLExceptionEmptyFileGuid {
            get {
                return ResourceManager.GetString("BLExceptionEmptyFileGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition file does not exist..
        /// </summary>
        internal static string BLExceptionMissingDefinition {
            get {
                return ResourceManager.GetString("BLExceptionMissingDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File storage directory does not exist..
        /// </summary>
        internal static string BLExceptionMissingDirectory {
            get {
                return ResourceManager.GetString("BLExceptionMissingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a mail server for &apos;{0}&apos;..
        /// </summary>
        internal static string BLExceptionMXRecordNotFound {
            get {
                return ResourceManager.GetString("BLExceptionMXRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File object not set..
        /// </summary>
        internal static string BLExceptionNullFile {
            get {
                return ResourceManager.GetString("BLExceptionNullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} GB.
        /// </summary>
        internal static string FormatGB {
            get {
                return ResourceManager.GetString("FormatGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} GBps.
        /// </summary>
        internal static string FormatGBPerSecond {
            get {
                return ResourceManager.GetString("FormatGBPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} KB.
        /// </summary>
        internal static string FormatKB {
            get {
                return ResourceManager.GetString("FormatKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} KBps.
        /// </summary>
        internal static string FormatKBPerSecond {
            get {
                return ResourceManager.GetString("FormatKBPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} MB.
        /// </summary>
        internal static string FormatMB {
            get {
                return ResourceManager.GetString("FormatMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} MBps.
        /// </summary>
        internal static string FormatMBPerSecond {
            get {
                return ResourceManager.GetString("FormatMBPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string FormatTimeSpanDays {
            get {
                return ResourceManager.GetString("FormatTimeSpanDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =============================================
        ///Evaluate Velodoc at http://www.velodoc.net.
        ///Get Velodoc at http://www.velodoc.com..
        /// </summary>
        internal static string Message_FileListFooter {
            get {
                return ResourceManager.GetString("Message_FileListFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///=============================================
        ///Please find below links to download files sent with Memba Velodoc:.
        /// </summary>
        internal static string Message_FileListHeader {
            get {
                return ResourceManager.GetString("Message_FileListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   • {0} ({1}) - {2}.
        /// </summary>
        internal static string Message_FileListItem {
            get {
                return ResourceManager.GetString("Message_FileListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VELODOC:: You have received files from {0}.
        /// </summary>
        internal static string Message_Subject {
            get {
                return ResourceManager.GetString("Message_Subject", resourceCulture);
            }
        }
    }
}
