//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memba.FileDownload.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memba.FileDownload.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality: {0}.
        /// </summary>
        internal static string DownloadFile_Confidentiality {
            get {
                return ResourceManager.GetString("DownloadFile_Confidentiality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type: {0}.
        /// </summary>
        internal static string DownloadFile_ContentType {
            get {
                return ResourceManager.GetString("DownloadFile_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        internal static string DownloadFile_DownloadState {
            get {
                return ResourceManager.GetString("DownloadFile_DownloadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date: {0}.
        /// </summary>
        internal static string DownloadFile_ExpirationDate {
            get {
                return ResourceManager.GetString("DownloadFile_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid: {0}.
        /// </summary>
        internal static string DownloadFile_FileGuid {
            get {
                return ResourceManager.GetString("DownloadFile_FileGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Name: {0}.
        /// </summary>
        internal static string DownloadFile_OriginalName {
            get {
                return ResourceManager.GetString("DownloadFile_OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage key: {0}.
        /// </summary>
        internal static string DownloadFile_ProviderKey {
            get {
                return ResourceManager.GetString("DownloadFile_ProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage provider: {0}.
        /// </summary>
        internal static string DownloadFile_ProviderName {
            get {
                return ResourceManager.GetString("DownloadFile_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal date: {0}.
        /// </summary>
        internal static string DownloadFile_RemovalDate {
            get {
                return ResourceManager.GetString("DownloadFile_RemovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request: {0}.
        /// </summary>
        internal static string DownloadFile_Request {
            get {
                return ResourceManager.GetString("DownloadFile_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan report:\r\n{0}.
        /// </summary>
        internal static string DownloadFile_ScanReport {
            get {
                return ResourceManager.GetString("DownloadFile_ScanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0} bytes.
        /// </summary>
        internal static string DownloadFile_Size {
            get {
                return ResourceManager.GetString("DownloadFile_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Download data --.
        /// </summary>
        internal static string DownloadFile_Title {
            get {
                return ResourceManager.GetString("DownloadFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name: {0}.
        /// </summary>
        internal static string DownloadFile_UserName {
            get {
                return ResourceManager.GetString("DownloadFile_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required to download..
        /// </summary>
        internal static string ExceptionAuthenticationRequired {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve download &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionCannotRetrieveDownload {
            get {
                return ResourceManager.GetString("ExceptionCannotRetrieveDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download no more available. Most probably file is expired. .
        /// </summary>
        internal static string ExceptionDownloadExpired {
            get {
                return ResourceManager.GetString("ExceptionDownloadExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for &quot;{0}&quot; refers to an invalid range..
        /// </summary>
        internal static string ExceptionInvalidRanges {
            get {
                return ResourceManager.GetString("ExceptionInvalidRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A precondition to the request &quot;{0}&quot; has failed: &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionPreconditionFailed {
            get {
                return ResourceManager.GetString("ExceptionPreconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request &quot;{0}&quot; has been cancelled or the client has been disconnected from the server..
        /// </summary>
        internal static string ExceptionRequestAbort {
            get {
                return ResourceManager.GetString("ExceptionRequestAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request type &quot;{0}&quot; is not implemented..
        /// </summary>
        internal static string ExceptionRequestTypeNotImplemented {
            get {
                return ResourceManager.GetString("ExceptionRequestTypeNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to request for &quot;{0}&quot; is too large (&gt;2GB)..
        /// </summary>
        internal static string ExceptionResponseTooLarge {
            get {
                return ResourceManager.GetString("ExceptionResponseTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; is not authorised to download &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionUnauthorizedDownload {
            get {
                return ResourceManager.GetString("ExceptionUnauthorizedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download successfully completed..
        /// </summary>
        internal static string MessageDownloadCompleted {
            get {
                return ResourceManager.GetString("MessageDownloadCompleted", resourceCulture);
            }
        }
    }
}
